apiVersion: v1
kind: Service
metadata:
  name: ai-platform-service
spec:
  type: NodePort
  selector:
    app: ai-platform
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 31000 # This matches the API_URL in the Frontend